### ISSUE TITLE
Reorganize output structure

### ISSUE THREAD

**Issue by lagillenwater** [UCDenver-ccp/Cartoomics#10]

**Comment by bsantan** [comment]
- Store knowledge graph files (edges, nodes.tsv's) in separate KnowledgeGraph directories
- Store nodevectors_node2vec.py, sparse_custom_node2vec_wrapper.py in a src folder (along with all other scripts/files) 
- Update command line options to include --knowledge-graph-dir instead of --input-dir

**Comment by bsantan** [comment]
done with PR #17
